// Mocks generated by Mockito 5.4.6 from annotations
// in jan_ghani_final/test/features/warehouse/warehouse_stock_inventory/product_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jan_ghani_final/features/warehouse/warehouse_stock_inventory/data/datasource/product_remote_datasource.dart'
    as _i3;
import 'package:jan_ghani_final/features/warehouse/warehouse_stock_inventory/data/model/product_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProductModel_0 extends _i1.SmartFake implements _i2.ProductModel {
  _FakeProductModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i3.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ProductModel>> getAll(String? warehouseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [warehouseId],
        ),
        returnValue:
            _i4.Future<List<_i2.ProductModel>>.value(<_i2.ProductModel>[]),
      ) as _i4.Future<List<_i2.ProductModel>>);

  @override
  _i4.Future<_i2.ProductModel?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i4.Future<_i2.ProductModel?>.value(),
      ) as _i4.Future<_i2.ProductModel?>);

  @override
  _i4.Future<_i2.ProductModel> add({
    required _i2.ProductModel? product,
    required double? initialQty,
    required String? userId,
    required String? userName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [],
          {
            #product: product,
            #initialQty: initialQty,
            #userId: userId,
            #userName: userName,
          },
        ),
        returnValue: _i4.Future<_i2.ProductModel>.value(_FakeProductModel_0(
          this,
          Invocation.method(
            #add,
            [],
            {
              #product: product,
              #initialQty: initialQty,
              #userId: userId,
              #userName: userName,
            },
          ),
        )),
      ) as _i4.Future<_i2.ProductModel>);

  @override
  _i4.Future<_i2.ProductModel> update({
    required _i2.ProductModel? oldProduct,
    required _i2.ProductModel? newProduct,
    required double? newQty,
    required String? userId,
    required String? userName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {
            #oldProduct: oldProduct,
            #newProduct: newProduct,
            #newQty: newQty,
            #userId: userId,
            #userName: userName,
          },
        ),
        returnValue: _i4.Future<_i2.ProductModel>.value(_FakeProductModel_0(
          this,
          Invocation.method(
            #update,
            [],
            {
              #oldProduct: oldProduct,
              #newProduct: newProduct,
              #newQty: newQty,
              #userId: userId,
              #userName: userName,
            },
          ),
        )),
      ) as _i4.Future<_i2.ProductModel>);

  @override
  _i4.Future<void> delete({
    required String? id,
    required _i2.ProductModel? product,
    required String? userId,
    required String? userName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #id: id,
            #product: product,
            #userId: userId,
            #userName: userName,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> skuExists(
    String? sku,
    String? warehouseId, {
    String? excludeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #skuExists,
          [
            sku,
            warehouseId,
          ],
          {#excludeId: excludeId},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> barcodeExists(
    String? barcode,
    String? warehouseId, {
    String? excludeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #barcodeExists,
          [
            barcode,
            warehouseId,
          ],
          {#excludeId: excludeId},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i3.ProductAuditLog>> getAuditLog(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuditLog,
          [productId],
        ),
        returnValue: _i4.Future<List<_i3.ProductAuditLog>>.value(
            <_i3.ProductAuditLog>[]),
      ) as _i4.Future<List<_i3.ProductAuditLog>>);
}
