// Mocks generated by Mockito 5.4.6 from annotations
// in jan_ghani_final/test/features/warehouse/supplier/mock_supplier_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jan_ghani_final/features/warehouse/supplier/data/supplier_repository.dart'
    as _i3;
import 'package:jan_ghani_final/features/warehouse/supplier/domian/supplier_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSupplierModel_0 extends _i1.SmartFake implements _i2.SupplierModel {
  _FakeSupplierModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SupplierRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupplierRepository extends _i1.Mock
    implements _i3.SupplierRepository {
  MockSupplierRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.SupplierModel>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.SupplierModel>>.value(<_i2.SupplierModel>[]),
      ) as _i4.Future<List<_i2.SupplierModel>>);

  @override
  _i4.Future<_i2.SupplierModel?> getById(String? supplierId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [supplierId],
        ),
        returnValue: _i4.Future<_i2.SupplierModel?>.value(),
      ) as _i4.Future<_i2.SupplierModel?>);

  @override
  _i4.Future<_i2.SupplierModel> insert(
    _i2.SupplierModel? supplier, {
    double? openingBalance = 0.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [supplier],
          {#openingBalance: openingBalance},
        ),
        returnValue: _i4.Future<_i2.SupplierModel>.value(_FakeSupplierModel_0(
          this,
          Invocation.method(
            #insert,
            [supplier],
            {#openingBalance: openingBalance},
          ),
        )),
      ) as _i4.Future<_i2.SupplierModel>);

  @override
  _i4.Future<_i2.SupplierModel> update(_i2.SupplierModel? supplier) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [supplier],
        ),
        returnValue: _i4.Future<_i2.SupplierModel>.value(_FakeSupplierModel_0(
          this,
          Invocation.method(
            #update,
            [supplier],
          ),
        )),
      ) as _i4.Future<_i2.SupplierModel>);

  @override
  _i4.Future<void> softDelete(String? supplierId) => (super.noSuchMethod(
        Invocation.method(
          #softDelete,
          [supplierId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.SupplierModel> payToSupplier({
    required String? supplierId,
    required double? amount,
    String? notes,
    String? userId,
    String? userName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #payToSupplier,
          [],
          {
            #supplierId: supplierId,
            #amount: amount,
            #notes: notes,
            #userId: userId,
            #userName: userName,
          },
        ),
        returnValue: _i4.Future<_i2.SupplierModel>.value(_FakeSupplierModel_0(
          this,
          Invocation.method(
            #payToSupplier,
            [],
            {
              #supplierId: supplierId,
              #amount: amount,
              #notes: notes,
              #userId: userId,
              #userName: userName,
            },
          ),
        )),
      ) as _i4.Future<_i2.SupplierModel>);

  @override
  _i4.Future<void> toggleStatus(
    String? supplierId,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleStatus,
          [
            supplierId,
            isActive,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
