// Mocks generated by Mockito 5.4.6 from annotations
// in jan_ghani_final/test/features/warehouse/warehouse_finance/warehouse_finance_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jan_ghani_final/features/warehouse/warehouse_finance/data/warehouse_finance_repository.dart'
    as _i3;
import 'package:jan_ghani_final/features/warehouse/warehouse_finance/domain/warehouse_finance_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWarehouseFinanceModel_0 extends _i1.SmartFake
    implements _i2.WarehouseFinanceModel {
  _FakeWarehouseFinanceModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCashTransactionModel_1 extends _i1.SmartFake
    implements _i2.CashTransactionModel {
  _FakeCashTransactionModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWarehouseFinanceSummary_2 extends _i1.SmartFake
    implements _i2.WarehouseFinanceSummary {
  _FakeWarehouseFinanceSummary_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WarehouseFinanceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWarehouseFinanceRepository extends _i1.Mock
    implements _i3.WarehouseFinanceRepository {
  MockWarehouseFinanceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WarehouseFinanceModel> getOrCreate() => (super.noSuchMethod(
        Invocation.method(
          #getOrCreate,
          [],
        ),
        returnValue: _i4.Future<_i2.WarehouseFinanceModel>.value(
            _FakeWarehouseFinanceModel_0(
          this,
          Invocation.method(
            #getOrCreate,
            [],
          ),
        )),
      ) as _i4.Future<_i2.WarehouseFinanceModel>);

  @override
  _i4.Future<List<_i2.CashTransactionModel>> getTransactions({
    String? entryType,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [],
          {
            #entryType: entryType,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i2.CashTransactionModel>>.value(
            <_i2.CashTransactionModel>[]),
      ) as _i4.Future<List<_i2.CashTransactionModel>>);

  @override
  _i4.Future<_i2.CashTransactionModel> addCashIn({
    required double? amount,
    String? notes,
    String? createdBy,
    String? createdByName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCashIn,
          [],
          {
            #amount: amount,
            #notes: notes,
            #createdBy: createdBy,
            #createdByName: createdByName,
          },
        ),
        returnValue: _i4.Future<_i2.CashTransactionModel>.value(
            _FakeCashTransactionModel_1(
          this,
          Invocation.method(
            #addCashIn,
            [],
            {
              #amount: amount,
              #notes: notes,
              #createdBy: createdBy,
              #createdByName: createdByName,
            },
          ),
        )),
      ) as _i4.Future<_i2.CashTransactionModel>);

  @override
  _i4.Future<_i2.CashTransactionModel> addPurchaseEntry({
    required double? amount,
    required String? poId,
    String? notes,
    String? createdBy,
    String? createdByName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPurchaseEntry,
          [],
          {
            #amount: amount,
            #poId: poId,
            #notes: notes,
            #createdBy: createdBy,
            #createdByName: createdByName,
          },
        ),
        returnValue: _i4.Future<_i2.CashTransactionModel>.value(
            _FakeCashTransactionModel_1(
          this,
          Invocation.method(
            #addPurchaseEntry,
            [],
            {
              #amount: amount,
              #poId: poId,
              #notes: notes,
              #createdBy: createdBy,
              #createdByName: createdByName,
            },
          ),
        )),
      ) as _i4.Future<_i2.CashTransactionModel>);

  @override
  _i4.Future<_i2.CashTransactionModel> addSupplierPayment({
    required double? amount,
    required String? supplierId,
    String? notes,
    String? createdBy,
    String? createdByName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSupplierPayment,
          [],
          {
            #amount: amount,
            #supplierId: supplierId,
            #notes: notes,
            #createdBy: createdBy,
            #createdByName: createdByName,
          },
        ),
        returnValue: _i4.Future<_i2.CashTransactionModel>.value(
            _FakeCashTransactionModel_1(
          this,
          Invocation.method(
            #addSupplierPayment,
            [],
            {
              #amount: amount,
              #supplierId: supplierId,
              #notes: notes,
              #createdBy: createdBy,
              #createdByName: createdByName,
            },
          ),
        )),
      ) as _i4.Future<_i2.CashTransactionModel>);

  @override
  _i4.Future<_i2.CashTransactionModel> addExpenseEntry({
    required double? amount,
    required String? expenseId,
    String? notes,
    String? createdBy,
    String? createdByName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addExpenseEntry,
          [],
          {
            #amount: amount,
            #expenseId: expenseId,
            #notes: notes,
            #createdBy: createdBy,
            #createdByName: createdByName,
          },
        ),
        returnValue: _i4.Future<_i2.CashTransactionModel>.value(
            _FakeCashTransactionModel_1(
          this,
          Invocation.method(
            #addExpenseEntry,
            [],
            {
              #amount: amount,
              #expenseId: expenseId,
              #notes: notes,
              #createdBy: createdBy,
              #createdByName: createdByName,
            },
          ),
        )),
      ) as _i4.Future<_i2.CashTransactionModel>);

  @override
  _i4.Future<_i2.WarehouseFinanceSummary> getSummary() => (super.noSuchMethod(
        Invocation.method(
          #getSummary,
          [],
        ),
        returnValue: _i4.Future<_i2.WarehouseFinanceSummary>.value(
            _FakeWarehouseFinanceSummary_2(
          this,
          Invocation.method(
            #getSummary,
            [],
          ),
        )),
      ) as _i4.Future<_i2.WarehouseFinanceSummary>);
}
